# Change baseurl before deploy
baseurl = "https://andytsang20.github.io/portfolio"
languageCode = "en-us"
title = "Hin Lam Tsang"
defaultContentLanguage = "en"

hasCJKLanguage = false



[pagination]
pagerSize = 5