# Change baseurl before deploy
baseurl = "https://andytsang20.com/"
languageCode = "en-us"
title = "Hin Lam Tsang"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

[params]
mainSections = ["posts"]
featuredImageField = "image"
rssFullText = true

[params.footer]
since = 2025
customText = "Hin Lam Tsang | Built with Hugo"

[params.sidebar]
emoji = "👋"
subtitle = "Master's Student in Global History | Project Management & VR Enthusiast"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.jpg"  # put your photo in "assets/img/avatar.jpg"

[params.social]
email = "andytsang20@gmail.com"
linkedin = "hin-lam-tsang-3a3815208"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 3

[pagination]
pagerSize = 5
